name: Deploy Infrastructure

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  TF_LOG: "INFO" # "DEBUG"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v3

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run: pip install --quiet -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v3

      - name: Run unit tests
        run: python test_app.py

  deploy_terraform_aws:
    name: deploy_terraform
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Terraform Format
        id: fmt
        run: terraform -chdir="./infra" fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform -chdir="./infra" init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform -chdir="./infra" validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform -chdir="./infra" plan -out=tfplan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: terraform -chdir="./infra" apply -input=false -auto-approve